group_imports = "StdExternalCrate"
imports_granularity = "Crate"
indent_style = "Block"
reorder_imports = true
error_on_line_overflow = true
format_code_in_doc_comments = true
wrap_comments = true
max_width = 120
doc_comment_code_block_width = 120
comment_width = 120
