name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  clippy:
    name: Clippy (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: rustup update stable

      - name: Make sure necessary tools are installed
        run: rustup component add clippy --toolchain stable

      - name: Setup rust-cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-bin: false

      - name: Run cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: rustup update stable

      - name: Setup rust-cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-bin: false

      - name: Run cargo test
        run: cargo test --all-features

  toml:
    name: Format (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        run: rustup update stable

      - name: Make sure necessary tools are installed
        run: rustup component add rustfmt --toolchain nightly

      - name: Setup rust-cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-bin: false

      - name: Install latest cargo-machete
        uses: taiki-e/install-action@cargo-machete

      - name: Install latest taplo
        uses: taiki-e/install-action@taplo

      - name: Check formatting (cargo fmt)
        run: cargo +nightly fmt --all --check

      - name: Check unused dependencies (cargo machete)
        run: cargo machete

      - name: Check TOML formatting (taplo)
        if: ${{ !contains(matrix.os, 'windows') }}
        run: taplo fmt --check --diff
